name: Push Workflow

on:
  push:
    branches:
      - main   # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Java JDK 17
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    # Step 3: Install Maven and ensure it has the necessary permissions
    - name: Set up Maven
      run: |
        chmod +x ./mvnw

    # Step 4: Download and install project dependencies
    - name: Install dependencies
      run: |
        ./mvnw clean install -DskipTests  # Install dependencies without running tests

    # Step 5: Build the project and run the server in the background
    - name: Build the project and run the server in the background
      run: |
        # Build the project (compile and package into a JAR)
        ./mvnw clean package
        # Run the Spring Boot application in the background
        java -jar ./target/*.jar --server.port=8080 &  # Run in background
        echo "Server started in the background"

    # Step 6: Run unit tests (if any exist in the project)
    - name: Run unit tests
      run: |
        ./mvnw test

    # Step 7: Check if the server is up and running (using curl to check health endpoint)
    - name: Check server health
      run: |
        curl -s 'http://localhost:8080/actuator/health' || echo "Server not reachable"

    # Optional: Create the jar in the target directory
    - name: Ensure jar is created
      run: |
        ls -l ./target/*.jar
